<?php echo $this->tag->getDoctype(); ?>
<?php
/*
  use MyCommon\Session\Pub\Lng;
  echo $this->doctype();
 * */
$di = $this->getDI();
$classviewmodtranslate =\MyCustomHelperClassTools::My_Core_Get_Classname('Viewmodtranslate');
?>

<html lang="<?php echo $di->controller_params_array['lng']; ?>">
    <head>
        <base href="<?php echo $this->getDI()->controller_params_array['html_base_path']; ?>" target="_self">
        <link href="<?php echo $di->controller_params_array['site_publicpath']; ?>components/com_mobile/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <title><?php echo $classviewmodtranslate::getKeyvalueFromKeyname('Ministry-of-National-Defence1'); ?></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="description" content="<?php echo $classviewmodtranslate::getKeyvalueFromKeyname('Ministry-of-National-Defence-Official-Web-Page1'); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=0">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="robots" content="index, follow">
        <meta name="keywords" content="<?php echo $classviewmodtranslate::getKeyvalueFromKeyname('Base-Keywords1'); ?>">
        <?php
        $collectionname = $di->controller_params_array['lng'] . 'js-mobile' . md5($this->view->getLayout());
        $objjscollection = $this->assets->collection($collectionname);

        $arr = array(
            5 => array('partialviewdir' => $di->controller_params_array['layout_mobile_view_folder'] . "dynpage/", 'partialviewname' => 'js-mobile'),
        );

        echo MyTags::MyCollectionJsGenerate($arr, $collectionname);
        if (MyCustomHelperCoreDi::Get_CacheCssJsEnabled()) {
            
        }
        ?>

        <?php
        $collectionname = $di->controller_params_array['lng'] . 'css-mobile'.md5($this->view->getLayout());
        $objcsscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array('partialviewdir' => $di->controller_params_array['layout_mobile_view_folder'] . "dynpage/", 'partialviewname' => 'css-mobile')
        );

        echo MyTags::MyCollectionCssGenerate($arr, $collectionname);
        if (MyCustomHelperCoreDi::Get_CacheCssJsEnabled()) {
            
        }
        ?>








        
        <!--ie hack. set the max width of the logo image in px, otherwise you canot change its size  -->
        <!--[if IE 7]>
               <style>
                       .fw-head.fw-logo img
                       {
                               max-width: 290px;
                       }
                       
                       .dm_header .logo-div img
                       {
                               max-width: 290px;
                       }
               </style>
       <![endif]-->
        <!--[if IE 8]>
                <style>
                        .fw-head .fw-logo img
                        {
                                max-width: 290px;
                        }
   
     
                        .dm_header .logo-div img
                        {
                                max-width: 290px;
                        }
                        *#dm div.dmHeader
                        {
                                _height:90px;
                                min-height:0px;
                        }
                        
                </style>
<![endif]-->


        <style type="text/css"> 
            /*a[href*="tel:"] , a[href*="sms:"] 
            {
                display:none !important;
            }*/
        </style>

    </head>


    <body id="dmRoot" class=" " style="overflow:auto;padding:0;margin:0;float:none;"  >


        <script>
            jQuery.DM.updateWidth();
            jQuery.DM.updateIOSHeight();
        </script>




        <div id="disabledImageZone" style="display:none;z-index:-1">

            <img id="imageZone" src="<?php echo $di->controller_params_array['base_path_with_site_publicpath']; ?>components/com_mobile/images/ajax-loader.gif" style="position:absolute;display:none"/>

        </div>

        <div id="dm" class='dmwr'>


            <div class="dm_wrapper matrix-var3 widgetStyle-2 matrix"> 
                <body dmwrapped="true" id="1251294294" class="dm-home-page">
                    <div dm:templateorder="4" dmtemplateid="MatrixLayout" class="dm-bfs dm-layout-home">
                        <div id="dmStyle_outerContainer" class="dmOuter"> 
                            <div id="dmStyle_innerContainer" class="dmInner"> <div class="dmLayoutWrapper matrix-var"> <a href="#dm_navGrouplink-anakinosisa" class="dmBackToTop" id="dmBackToTop"></a> 
                                    <div id="iscrollBody"> 
                                        <div id="site_content" class="hasDmMatrixNav"> 

                                            <?php echo CHMod20130918MHeader::getHeader(); ?>


                                            <div id="innerBar" class="innerBar display_None"> <a id="dmBackBtn" class="uiBtn" back-title="Back"> <span id="dmBackArrow"></span> 
                                                </a> 
                                                <div id="slideDownTrigger" class="uiBtn slideDownTrigger"> <div class="btnStripe"></div> 
                                                    <div class="btnStripe"></div> 
                                                    <div class="btnStripe"></div> 
                                                </div> 
                                            </div> 
                                            <ul class="dmn dmLayoutNav hiddenNavPlaceHolder navPlaceHolder dmDisplay_None"></ul> 
                                            <div id="slideDownNav" class="dmn dmLayoutNav"> <ul class="dmNavigationStyle_1 dmNavigation dmn  dmShowInnerBar"> 
                                                    <li class="${li_class} listBtnHidden dmHideFromNav   navListLi" id="listBtnHidden"> <a href="%24%7bhref%7d.html" dm_dont_rewrite_url="true" class="${a_class}" target="${a_target}"> <span class="navItemIconBg"> <span class="navItemIcon"></span> 
                                                            </span> 
                                                            <span class="navItemText"></span> 
                                                            <span class="navItemArrowBg"> <span class="navItemArrow"></span> 
                                                            </span> 
                                                        </a> 
                                                    </li> 

                                                </ul> 
                                            </div> 
                                            <div dmwrapped="true" id="1251294294" class="dmBody u_dmStyle_template_home dm-home-page"> <div id="allWrapper" class="allWrapper"><!-- navigation placeholders --> <div id="navWrapper" class="navWrapper"> <div id="hiddenNavPlaceHolder" class="hiddenNavPlaceHolder navPlaceHolder dmDisplay_None" navplaceholder="true"></div> 
                                                        <div id="backToHomePlaceHolder" class="backToHomePlaceHolder navPlaceHolder" navplaceholder="true"></div> 
                                                        <hr class="dmDivider" style="min-height: 2px; border:none; background:grey" id="1707057942"/> <span style="clear:both;display:block" id="1787044681"></span> 
                                                        <div id="newNavigationSubNavPlaceHolder" class="newNavigationSubNavPlaceHolder navPlaceHolder dmEmptyNav" navplaceholder="true"> <ul class="default dmNav dmn dmNavCustom" id="dm_navGroup00s" shape_class="default" view_type="sub"></ul> 
                                                            <div class="noFloat"></div> 
                                                        </div> 
                                                        <span style="clear:both;display:block" id="1528412969"></span> 
                                                    </div> 

                                                    <?php
                                                    echo $this->getContent();
                                                    ?>
                                                    <span style="clear:both;display:block" id="1221542405"></span> 
                                                </div> 




                                                <?php echo CHMod20130918MFooter::getFooter(); ?>   

                                            </div>

                                        </div> 
                                    </div> 
                                </div> 
                            </div> 

                        </div>
                    </div>
                </body>
            </div>



            <div id="fb-root"></div>


    </body>


</html>