<?php
$di = Phalcon\DI::getDefault();
?>
<?php echo $this->tag->getDoctype(); ?>
<?php $this->partial($di->controller_params_array['template']['template_view_dir']."license") ?>
<?php $assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path']; 
$template_admin_name=$di->controller_params_array['template']['template_admin_name'];
?>

<!--[if IE 8]> <html lang="en" class="ie8 no-js" data-ng-app="MetronicApp"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js" data-ng-app="MetronicApp"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" data-ng-app="MetronicApp">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <base href="<?php echo $di->controller_params_array['html_base_path']; ?>">
        <title data-ng-bind="'<?php echo $di->controller_params_array['settings']['site_title']; ?> - ' + $state.current.data.pageTitle"></title>

        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>

        <!-- BEGIN GLOBAL MANDATORY STYLES -->





        <!--<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>-->



        <?php
        $collectionname = 'cssGlobal'.$template_admin_name;
        $objcsscollection = $this->assets->collection($collectionname);

        $arr = array(
            1 => array(
                'path' => 'custom/css/',
                'filename' => 'customfirst.css'
            ),
            5 => array(
                'remoteurl' => 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all'
            ),
            10 => array(
                'path' => $assetspath . 'global/plugins/font-awesome/css/',
                'filename' => 'font-awesome.css'
            ),
            20 => array(
                'path' => $assetspath . 'global/plugins/simple-line-icons/',
                'filename' => 'simple-line-icons.css'
            ),
            30 => array(
                'path' => $assetspath . 'global/plugins/bootstrap/css/',
                'filename' => 'bootstrap.css'
            ),
            40 => array(
                'path' => $assetspath . 'global/plugins/uniform/css/',
                'filename' => 'uniform.default.css'
            ),
            50 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-switch/css/',
                'filename' => 'bootstrap-switch.css'
            )
        );

        echo MyTags::MyCollectionCssGenerate($arr, $collectionname);
        
        ?>

        <!-- END GLOBAL MANDATORY STYLES -->

        <!-- BEGIN DYMANICLY LOADED CSS FILES(all plugin and page related styles must be loaded between GLOBAL and THEME css files ) -->
        <link id="ng_load_plugins_before"/>
        <!-- END DYMANICLY LOADED CSS FILES -->

        <!-- BEGIN THEME STYLES -->
        <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->


        <?php
        $collectionname = 'cssTheme'.$template_admin_name . $di->controller_params_array['template']['template_admin_theme'] . $di->controller_params_array['template']['template_admin_theme_color'];
        $objcsscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array(
                'path' => $assetspath . 'global/css/',
                'filename' => 'components.css'
            ),
            1 => array(
                'path' => $assetspath . 'global/css/',
                'filename' => 'plugins.css'
            ),
            2 => array(
                'path' => $assetspath . 'admin/layout/css/',
                'filename' => 'layout.css'
            ),
            3 => array(
                'path' => $assetspath . 'admin/layout/css/themes/',
                'filename' => $di->controller_params_array['template']['template_admin_theme_color'] . '.css'
            ),
            4 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-datetimepicker/css/',
                'filename' => 'bootstrap-datetimepicker.min.css'
            ),
            5 => array(
                'path' => $assetspath . 'admin/layout/css/',
                'filename' => 'custom.css'
            ),
            
        );

        echo MyTags::MyCollectionCssGenerate($arr, $collectionname);
        
        ?>
        <!-- END THEME STYLES -->

        <link rel="shortcut icon" href="/custom/images/favicon.ico"/>
    </head>
    <!-- END HEAD -->


    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
    <body ng-controller="AppController" class="page-header-fixed page-sidebar-closed-hide-logo page-quick-sidebar-over-content page-on-load" ng-class="{'page-container-bg-solid': settings.layout.pageBodySolid, 'page-sidebar-closed': settings.layout.pageSidebarClosed}">


        <!-- BEGIN PAGE SPINNER -->
        <div ng-spinner-bar class="page-spinner-bar">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
        <!-- END PAGE SPINNER -->

        <!-- BEGIN HEADER -->
        <div data-ng-include="<?php echo '\'' . MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'outer-header')) . '\''; ?>" data-ng-controller="HeaderController" class="page-header navbar navbar-fixed-top my-edit-js-control">
        </div>
        <!-- END HEADER -->

        <div class="clearfix">
        </div>

        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div data-ng-include="<?php echo '\'' . MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'outer-sidebar')) . '\''; ?>" data-ng-controller="SidebarController" class="page-sidebar-wrapper">			
            </div>
            <!-- END SIDEBAR -->

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <!-- BEGIN STYLE CUSTOMIZER(optional) -->
                    <!-- Pan Pan start fix hide search and theme bar on modal with class my-edit-js-control 06/05/2015 -->
                    <div data-ng-include="<?php echo '\'' . MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'outer-theme-panel')) . '\''; ?>" data-ng-controller="ThemePanelController" class="theme-panel hidden-xs hidden-sm my-edit-js-control">				
                        <!-- Pan Pan end fix hide search and theme bar on modal with class my-edit-js-control 06/05/2015 -->
                    </div>
                    <!-- END STYLE CUSTOMIZER -->

                    <!-- BEGIN ACTUAL CONTENT -->
                    <div ui-view class="fade-in-up" id="actualcontent">
                    </div> 
                    <!-- END ACTUAL CONTENT -->
                </div>	
            </div>
            <!-- END CONTENT -->

            <!-- BEGIN QUICK SIDEBAR -->
            <a href="javascript:;" class="page-quick-sidebar-toggler"><i class="icon-close"></i></a>
            <div data-ng-include="<?php echo '\'' . MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'outer-quick-sidebar')) . '\''; ?>" data-ng-controller="QuickSidebarController" class="page-quick-sidebar-wrapper"></div>
            <!-- END QUICK SIDEBAR -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div data-ng-include="<?php echo '\'' . MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'outer-footer')) . '\''; ?>" data-ng-controller="FooterController" class="page-footer">
        </div>
        <!-- END FOOTER -->

        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

        <!-- BEGIN CORE JQUERY PLUGINS -->
        <!--[if lt IE 9]>
        <script src="../../../assets/global/plugins/respond.min.js"></script>
        <script src="../../../assets/global/plugins/excanvas.min.js"></script> 
        <![endif]
        <script src="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE, array('helperpage' => 'js-custom-first')); // '/b2b/' . $di->controller_params_array['lng'] . '/admin/dynhelperpage/js-custom-first/1.js';  ?>"></script>-->
        <?php
        $collectionname = 'jsJqueryCorePlugins'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array('partialviewdir' => $di->controller_params_array['template']['template_view_dir'] . "index/dynhelperpage/", 'partialviewname' => 'js-custom-first'),
            //0 => array(
            //    'localurl' => '/b2b/' . $di->controller_params_array['lng'] . '/admin/dynhelperpage/js-custom-first/1.js',
            //),
            2 => array(
                'path' => $assetspath . 'global/plugins/',
                'filename' => 'jquery.min.js'
            ),
            10 => array(
                'path' => 'custom/js/',
                'filename' => 'customfirst.js'
            ),
            20 => array(
                'path' => $assetspath . 'global/plugins/',
                'filename' => 'jquery-migrate.min.js'
            ),
            30 => array(
                'path' => $assetspath . 'global/plugins/jquery-ui/',
                'filename' => 'jquery-ui.min.js'
            ),
            40 => array(
                'path' => $assetspath . 'global/plugins/bootstrap/js/',
                'filename' => 'bootstrap.min.js'
            ),
            50 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-hover-dropdown/',
                'filename' => 'bootstrap-hover-dropdown.min.js'
            ),
            60 => array(
                'path' => $assetspath . 'global/plugins/jquery-slimscroll/',
                'filename' => 'jquery.slimscroll.min.js'
            ),
            70 => array(
                'path' => $assetspath . 'global/plugins/',
                'filename' => 'jquery.blockui.min.js'
            ),
            80 => array(
                'path' => $assetspath . 'global/plugins/',
                'filename' => 'jquery.cokie.min.js'
            ),
            90 => array(
                'path' => $assetspath . 'global/plugins/uniform/',
                'filename' => 'jquery.uniform.min.js'
            ),
            95 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-switch/js/',
                'filename' => 'bootstrap-switch.min.js'
            ),
            99 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-confirmation/',
                'filename' => 'bootstrap-confirmation.min.js'
            ),
        );

        echo MyTags::MyCollectionJsGenerate($arr, $collectionname);
        //$tst=$this->assets->outputInlineJs($collectionname);
        

        //$tst=$this->assets->outputInlineJs($collectionname);
        ?>


        <!-- END CORE JQUERY PLUGINS -->

        <!-- BEGIN CORE ANGULARJS PLUGINS -->

        <?php
        $collectionname = 'jsAngularCorePlugins'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            0 => array(
                'path' => $assetspath . 'global/plugins/angularjs/',
                'filename' => 'angular.min.js'
            ),
            1 => array(
                'path' => $assetspath . 'global/plugins/angularjs/',
                'filename' => 'angular-sanitize.min.js'
            ),
            2 => array(
                'path' => $assetspath . 'global/plugins/angularjs/',
                'filename' => 'angular-touch.min.js'
            ),
            3 => array(
                'path' => $assetspath . 'global/plugins/angularjs/plugins/',
                'filename' => 'angular-ui-router.min.js'
            ),
            4 => array(
                'path' => $assetspath . 'global/plugins/angularjs/plugins/',
                'filename' => 'ocLazyLoad.min.js'
            ),
            5 => array(
                'path' => $assetspath . 'global/plugins/angularjs/plugins/',
                'filename' => 'ui-bootstrap-tpls.min.js'
            )
        );
        echo MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>

        <!-- END CORE ANGULARJS PLUGINS -->

        <!-- BEGIN APP LEVEL ANGULARJS SCRIPTS 
        <script src="/b2b/<?php echo $di->controller_params_array['lng']; ?>/admin/dynhelperpage/js-app/1.js"></script> -->
        <?php
        $collectionname = 'jsAngularApp'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            //0 => array(
            //    'path' => 'custom/'.$di->controller_params_array['template']['template_admin_path'] .'theme/templates/admin/angularjs/js/',
            //    'filename' => 'app.js'
            //),
            //0 => array(
            //    'path' => 'http://phalconphp.com.local/b2b/admin/dynhelperpage/',
            //    'filename' => 'js-app/'
            //),
            0 => array('partialviewdir' => $di->controller_params_array['template']['template_view_dir'] . "index/dynhelperpage/", 'partialviewname' => 'js-app'),
            //0 => array(
            //    'localurl' => '/b2b/' . $di->controller_params_array['lng'] . '/admin/dynhelperpage/js-app/1.js',
            //),
            10 => array(
                'path' => $di->controller_params_array['template']['template_admin_path'] . 'theme/templates/admin/angularjs/js/',
                'filename' => 'directives.js'
            ),
            20 => array(
                'path' => $assetspath . 'global/plugins/',
                'filename' => 'jquery.pulsate.min.js'
            ),
            30 => array(
                'path' => $assetspath . 'global/plugins/jquery-bootpag/',
                'filename' => 'jquery.bootpag.min.js'
            ),
            40 => array(
                'path' => $assetspath . 'global/plugins/bootstrap-datetimepicker/js/',
                'filename' => 'bootstrap-datetimepicker.min.js'
            ),
        );
        echo MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>

        <!-- END APP LEVEL ANGULARJS SCRIPTS -->

        <!-- BEGIN APP LEVEL JQUERY SCRIPTS -->


        <?php
        $collectionname = 'jsJqueryApp'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            0 => array(
                'path' => $assetspath . 'global/scripts/',
                'filename' => 'metronic.js'
            ),
            10 => array(
                'path' => $assetspath . 'admin/layout/scripts/',
                'filename' => 'layout.js'
            ),
            20 => array(
                'path' => $assetspath . 'admin/layout/scripts/',
                'filename' => 'quick-sidebar.js'
            ),
            30 => array(
                'path' => $assetspath . 'admin/layout/scripts/',
                'filename' => 'demo.js'
            ),
            40 => array(
                'path' => $di->controller_params_array['template']['template_admin_custom_path'] . 'js/',
                'filename' => 'ui-general.js'
            ),
            50 => array('partialviewdir' => $di->controller_params_array['template']['template_view_dir'] . "index/dynhelperpage/", 'partialviewname' => 'js-components-pickers'),
            60 => array(
                'path' => 'custom/js/',
                'filename' => 'customend.js'
            ),
            90 => array('partialviewdir' => $di->controller_params_array['template']['template_view_dir'] . "index/dynhelperpage/", 'partialviewname' => 'js-custom-end'),
                //90 => array(
                //    'localurl' => '/b2b/' . $di->controller_params_array['lng'] . '/admin/dynhelperpage/js-custom-end/1.js',
                //),
        );
        echo MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>

        <!--<script src="<?php echo '/b2b/' . $di->controller_params_array['lng'] . '/admin/dynhelperpage/js-custom-end/1.js'; ?>"></script>-->

        <!-- END APP LEVEL JQUERY SCRIPTS -->

        <script type="text/javascript">
                    /* Init Metronic's core jquery plugins and layout scripts */
                    $(document).ready(function () {
                        Metronic.init(); // Run metronic theme
                        Metronic.setAssetsPath(<?php echo '\'' . $assetspath . '\''; ?>); // Set the assets folder path			
                    });
        </script>
        <!-- END JAVASCRIPTS -->

        <?php echo $this->getContent() ?>
        <?php
//$r = AutoGenCustomHelperB2bAio::$Core_Tbl_Settings;
//$t=8;
//echo $r;
        ?>
    </body>
    <!-- END BODY -->
</html>


