<?php
$di = Phalcon\DI::getDefault();
?>
<?php echo $this->tag->getDoctype(); ?>
<?php $this->partial($di->controller_params_array['template']['template_view_dir']."license") ?>
<?php $assetspath = $di->controller_params_array['template_admin_path_with_assets_path']; 
$template_admin_name=$di->controller_params_array['template']['template_admin_name'];
?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js" data-ng-app="MetronicApp"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js" data-ng-app="MetronicApp"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" data-ng-app="MetronicApp">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
<base href="<?php echo $di->controller_params_array['template_admin_path_base']; ?>">
        <title data-ng-bind="'Metronic AngularJS | ' + $state.current.data.pageTitle"></title>

        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>

        <!-- BEGIN GLOBAL MANDATORY STYLES -->





        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>



        <?php
        $collectionname = 'cssGlobal'.$template_admin_name;
        $objcsscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/font-awesome/css/',
                'filename' => 'font-awesome.css'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/simple-line-icons/',
                'filename' => 'simple-line-icons.css'
            ),
            2 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap/css/',
                'filename' => 'bootstrap.css'
            ),
            3 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/uniform/css/',
                'filename' => 'uniform.default.css'
            ),
            4 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap-switch/css/',
                'filename' => 'bootstrap-switch.css'
            )
        );

        MyTags::MyCollectionCssGenerate($arr, $collectionname);
        

        /* $collectionname = 'cssGlobal'.$template_admin_name;
          $collectioncss = 'tmp/' . $collectionname . '.css';
          $collectionfordeletecss = 'tmp/fordelete/' . $collectionname . '.css';

          $path = $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/font-awesome/css/';
          $filename = 'font-awesome.css';
          $number = 1;
          MyTags::MyCollectionCss($collectionfordeletecss, $path, $filename, $number);

          $path = $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/simple-line-icons/';
          $filename = 'simple-line-icons.css';
          $number++;
          MyTags::MyCollectionCss($collectionfordeletecss, $path, $filename, $number);

          $path = $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap/css/';
          $filename = 'bootstrap.css';
          $number++;
          MyTags::MyCollectionCss($collectionfordeletecss, $path, $filename, $number);

          $path = $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/uniform/css/';
          $filename = 'uniform.default.css';
          $number++;
          MyTags::MyCollectionCss($collectionfordeletecss, $path, $filename, $number);

          $path = $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap-switch/css/';
          $filename = 'bootstrap-switch.css';
          $number++;
          MyTags::MyCollectionCss($collectionfordeletecss, $path, $filename, $number);

          $css = $this->assets->collection($collectionname);

          $css
          ->setTargetPath($collectioncss)
          ->setPrefix('')
          ->setTargetUri($collectioncss);
          for ($i = 1; $i <= $number; $i++) {
          $css->addCss($collectionfordeletecss . $i, true);
          }

          $css->join(true)
          ->addFilter(new Phalcon\Assets\Filters\Cssmin());

           */
        ?>

        <!-- END GLOBAL MANDATORY STYLES -->

        <!-- BEGIN DYMANICLY LOADED CSS FILES(all plugin and page related styles must be loaded between GLOBAL and THEME css files ) -->
        <link id="ng_load_plugins_before"/>
        <!-- END DYMANICLY LOADED CSS FILES -->

        <!-- BEGIN THEME STYLES -->
        <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->


        <?php
        $collectionname = 'cssTheme'.$template_admin_name.$di->controller_params_array['template_admin_theme'].$di->controller_params_array['template_admin_theme_color'];
        $objcsscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/css/',
                'filename' => 'components.css'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/css/',
                'filename' => 'plugins.css'
            ),
            2 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/css/',
                'filename' => 'layout.css'
            ),
            3 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/css/themes/',
                'filename' => $di->controller_params_array['template_admin_theme_color'].'.css'
            ),
            4 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/css/',
                'filename' => 'custom.css'
            )
        );

        MyTags::MyCollectionCssGenerate($arr, $collectionname);
        
        ?>
        <!-- END THEME STYLES -->

        <link rel="shortcut icon" href="favicon.ico"/>
    </head>
    <!-- END HEAD -->


    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
    <body ng-controller="AppController" class="page-header-fixed page-sidebar-closed-hide-logo page-quick-sidebar-over-content page-on-load" ng-class="{'page-container-bg-solid': settings.layout.pageBodySolid, 'page-sidebar-closed': settings.layout.pageSidebarClosed}">


        <!-- BEGIN PAGE SPINNER -->
        <div ng-spinner-bar class="page-spinner-bar">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
        <!-- END PAGE SPINNER -->

        <!-- BEGIN HEADER -->
        <div data-ng-include="<?php echo '\'' . $di->controller_params_array['template_admin_path_base'] . 'tpl/header.html\''; ?>" data-ng-controller="HeaderController" class="page-header navbar navbar-fixed-top">
        </div>
        <!-- END HEADER -->

        <div class="clearfix">
        </div>

        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div data-ng-include="<?php echo '\'' . $di->controller_params_array['template_admin_path_base'] . 'tpl/sidebar.html\''; ?>" data-ng-controller="SidebarController" class="page-sidebar-wrapper">			
            </div>
            <!-- END SIDEBAR -->

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <!-- BEGIN STYLE CUSTOMIZER(optional) -->
                    <div data-ng-include="<?php echo '\'' . $di->controller_params_array['template_admin_path_base'] . 'tpl/theme-panel.html\''; ?>" data-ng-controller="ThemePanelController" class="theme-panel hidden-xs hidden-sm">				
                    </div>
                    <!-- END STYLE CUSTOMIZER -->

                    <!-- BEGIN ACTUAL CONTENT -->
                    <div ui-view class="fade-in-up">
                    </div> 
                    <!-- END ACTUAL CONTENT -->
                </div>	
            </div>
            <!-- END CONTENT -->

            <!-- BEGIN QUICK SIDEBAR -->
            <a href="javascript:;" class="page-quick-sidebar-toggler"><i class="icon-close"></i></a>
            <div data-ng-include="<?php echo '\'' . $di->controller_params_array['template_admin_path_base'] . 'tpl/quick-sidebar.html\''; ?>" data-ng-controller="QuickSidebarController" class="page-quick-sidebar-wrapper"></div>
            <!-- END QUICK SIDEBAR -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div data-ng-include="<?php echo '\'' . $di->controller_params_array['template_admin_path_base'] . 'tpl/footer.html\''; ?>" data-ng-controller="FooterController" class="page-footer">
        </div>
        <!-- END FOOTER -->

        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

        <!-- BEGIN CORE JQUERY PLUGINS -->
        <!--[if lt IE 9]>
        <script src="../../../assets/global/plugins/respond.min.js"></script>
        <script src="../../../assets/global/plugins/excanvas.min.js"></script> 
        <![endif]-->

        <?php
        $collectionname = 'jsJqueryCorePlugins'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);

        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/',
                'filename' => 'jquery.min.js'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/',
                'filename' => 'jquery-migrate.min.js'
            ),
            2 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap/js/',
                'filename' => 'bootstrap.min.js'
            ),
            3 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap-hover-dropdown/',
                'filename' => 'bootstrap-hover-dropdown.min.js'
            ),
            4 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/jquery-slimscroll/',
                'filename' => 'jquery.slimscroll.min.js'
            ),
            5 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/',
                'filename' => 'jquery.blockui.min.js'
            ),
            6 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/',
                'filename' => 'jquery.cokie.min.js'
            ),
            7 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/uniform/',
                'filename' => 'jquery.uniform.min.js'
            ),
            8 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/bootstrap-switch/js/',
                'filename' => 'bootstrap-switch.min.js'
            ),
        );

        MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>


        <!-- END CORE JQUERY PLUGINS -->

        <!-- BEGIN CORE ANGULARJS PLUGINS -->

        <?php
        $collectionname = 'jsAngularCorePlugins'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/',
                'filename' => 'angular.min.js'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/',
                'filename' => 'angular-sanitize.min.js'
            ),
            2 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/',
                'filename' => 'angular-touch.min.js'
            ),
            3 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/plugins/',
                'filename' => 'angular-ui-router.min.js'
            ),
            4 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/plugins/',
                'filename' => 'ocLazyLoad.min.js'
            ),
            5 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/plugins/angularjs/plugins/',
                'filename' => 'ui-bootstrap-tpls.min.js'
            )
        );
        MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>

        <!-- END CORE ANGULARJS PLUGINS -->

        <!-- BEGIN APP LEVEL ANGULARJS SCRIPTS -->
        <?php
        $collectionname = 'jsAngularApp'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/templates/admin/angularjs/js/',
                'filename' => 'app.js'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/templates/admin/angularjs/js/',
                'filename' => 'directives.js'
            )
        );
        MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>

        <!-- END APP LEVEL ANGULARJS SCRIPTS -->

        <!-- BEGIN APP LEVEL JQUERY SCRIPTS -->


        <?php
        $collectionname = 'jsJqueryApp'.$template_admin_name;
        $objjscollection = $this->assets->collection($collectionname);
        $arr = array(
            0 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/global/scripts/',
                'filename' => 'metronic.js'
            ),
            1 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/scripts/',
                'filename' => 'layout.js'
            ),
            2 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/scripts/',
                'filename' => 'quick-sidebar.js'
            ),
            3 => array(
                'path' => $di->controller_params_array['template_admin_path'] .'theme/assets/admin/layout/scripts/',
                'filename' => 'demo.js'
            )
        );
        MyTags::MyCollectionJsGenerate($arr, $collectionname);
        
        ?>



        <!-- END APP LEVEL JQUERY SCRIPTS -->

        <script type="text/javascript">
                    /* Init Metronic's core jquery plugins and layout scripts */
                    $(document).ready(function () {
                        Metronic.init(); // Run metronic theme
                        Metronic.setAssetsPath(<?php echo '\'' . $assetspath . '\''; ?>); // Set the assets folder path			
                    });
        </script>
        <!-- END JAVASCRIPTS -->

        <?php echo $this->getContent() ?>
        <?php
        //$r = AutoGenCustomHelperB2bAio::$Core_Tbl_Settings;
//$t=8;
        //echo $r;
        ?>

    </body>
    <!-- END BODY -->
</html>


