<?php $assetspath = $di->controller_params_array['template']['template_admin_path_assets']; ?>
<!-- BEGIN PAGE HEADER-->
<?php
echo Metronic362CCustomHelperAjax::get_div_ajax_small_stack1();
echo Metronic362CCustomHelperAjax::get_div_ajax_full();
$di->controller_params_array['page_header']['pagetitle']='Application Settings Static Translates';
$di->controller_params_array['page_header']['breadcrumb']['title']='Application Settings Static Translates';
echo Metronic362CCustomHelperInnerPageHelperHeader::Get_Page_Header();
?>
<!-- END PAGE HEADER-->
<!-- BEGIN MAIN CONTENT -->
<div class="row">
    <div class="col-md-12">
        <!--        <div class="note note-danger">
                    <p>
                        NOTE: The below datatable is not connected to a real database so the filter and sorting is just simulated for demo purposes only.
                    </p>
                </div>-->
        <!-- Begin: life time stats -->
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <script>
                        /*function bootstrap_confirmation() {
                         //alert("yes");
                         $('[data-toggle="confirmation"]').confirmation();
                         //$('[data-toggle="confirmation-singleton"]').confirmation({
                         //    singleton: true
                         //});
                         //$('[data-toggle="confirmation-popout"]').confirmation({
                         //    popout: true
                         //});
                         }*/
                    </script>
                    <div id="bootstrap_alert">
                    </div>
                    <i class="fa fa-table"></i>Settings Static Translates Tables
                </div>
                <div class="actions">
                    <a href="/b2b/<?php echo $di->controller_params_array['lng']; ?>/admin/dynhelperpage/<?php echo $di->controller_params_array['settings']['Helper_Page_Modal_Operations']; ?>/<?php echo $di->controller_params_array['settings']['Action_Add']; ?>/<?php echo AGCHParams::$Settings_Param2_Static_Translates_2; ?>/<?php echo AGCHParams::$Settings_New_Record_Identifier_Id_2; ?>/" 
                       data-target="#ajax-small-stack1" 
                       data-toggle="modal"
                       class="btn default yellow-stripe">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                            New Alias </span>
                    </a>                



                    <div class="btn-group">
                        <a class="btn default yellow-stripe" href="#" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-480">
                                Tools </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">                            
                            <li>
                                <a href="#" class="export-to-csv">
                                    Export to CSV </a>
                            </li>
                            <li>
                                <a href="#" class="export-to-excel">
                                    Export to Excel </a>
                            </li>
                            <li>
                                <a href="#" class="export-to-pdf">
                                    Export to PDF </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">
                                    Print Tables </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-container">
                    <div class="table-actions-wrapper">
                        <span>
                        </span>
                        <select class="table-group-action-input form-control input-inline input-small input-sm">
                            <option value="">Select...</option>
                            <option value="Cancel">Cancel</option>
                            <option value="Cancel">Hold</option>
                            <option value="Cancel">On Hold</option>
                            <option value="Close">Close</option>
                        </select>
                        <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> Submit</button>
                    </div>
                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                            <tr role="row" class="heading">
                                <th width="2%">
                                    <input type="checkbox" class="group-checkable">
                                </th>
                                <th width="1%">
                                    Seq#
                                </th>
                                <th width="7%">
                                    Status
                                </th>
                                <th width="15%">
                                    Alias Key
                                </th>
                                <?php
                                $collngwidth = 60 / count($di->controller_params_array['lngarr']);
                                foreach ($di->controller_params_array['lngarr'] as $key => $value) {
                                    echo '<th width="' . $collngwidth . '%">
                                    ' . $di->controller_params_array['static_translates'][$value . '-label'] . '
                                </th>';
                                }
                                ?>

                                <th width="13%">
                                    Actions
                                </th>
                            </tr>
                            <tr role="row" class="filter">
                                <td>
                                </td>
                                <td>

                                </td>
                                <td>
                                    <select class="form-control form-filter input-sm" name="order_status">
                                        <option value="<?php echo AGCHParams::$Static_Status_All; ?>">All...</option>
                                        <option value="<?php echo AGCHParams::$Static_Status_Active; ?>">Active</option>
                                        <option value="<?php echo AGCHParams::$Static_Status_Disabled; ?>">Disabled</option>
                                        <option value="<?php echo AGCHParams::$Static_Status_Trashed; ?>">Trashed</option>
                                    </select>
                                </td>
                                <td>
                                    <input type="text" class="form-control form-filter input-sm" name="search-alias">
                                </td>
                                <?php
                                foreach ($di->controller_params_array['lngarr'] as $key => $value) {
                                    echo '<td>
                                    <input type="text" class="form-control form-filter input-sm" name="search-lng-' . $value . '">
                                </td>';
                                }
                                ?>


                                <td>
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                    </div>
                                    <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<!-- END MAIN CONTENT -->

<!-- BEGIN PAGE LEVEL PLUGINS 
<script src="/<?php echo $assetspath; ?>global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js" type="text/javascript"></script>-->
<!-- END MAIN JS -->
<script type="text/javascript">
    runeveryinner();
    var MyModalInitPage = function () {
        Form1Click();
    }
    var MyModalOnClose = function () {
        //alert('close');
        grid.getDataTable().ajax.reload();
    }

    TableAjax.init();

    //handleBootstrapConfirmation();
</script>

