<?php
$di = \Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
?>
<!-- BEGIN PAGE HEADER-->

<?php
echo Metronic454CCustomHelperAjax::get_div_ajax_small_stack1();
echo Metronic454CCustomHelperAjax::get_div_ajax_full();
?>
<?php
echo \B2b\Models\CoreModels\PpB2bAdminMetronic454PluginPageHelperHeader::Get_Page_Header();
?>

<!-- END PAGE HEADER-->
<!-- BEGIN MAIN CONTENT -->
<?php
echo B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::Get_Page_DataTableAjax();
?>

<!-- END MAIN CONTENT -->

<!-- BEGIN PAGE LEVEL PLUGINS 
<script src="/<?php echo $assetspath; ?>global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js" type="text/javascript"></script>-->
<!-- END MAIN JS -->
<script type="text/javascript">
    runeveryinner();
    var MyModalInitPage = function () {
        Form1Click();
    }
    var MyModalOnClose = function () {
        //alert('close');
        grid.getDataTable().ajax.reload();
    }

    myaoColumns = <?php echo $di->controller_params_array[CHCrmCParams::$keyarrDataTableAjax]['myaoColumns']; ?>;

<?php
echo B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::Get_Js_Function_MyRunForm('$(\'#datatableajax-add-record\').click();');
?>

<?php $pluginarrparams = $di->controller_params_array[\CHCrmCParams::$keyarrDataTableAjax]; ?>
    $('#fkcategoryapomiosi').on('change', function (e) {
        var mydisablefrom = true;
        if ($(this).val() != -1)
        {
            mydisablefrom = false;
        }
        resetform(mydisablefrom);
    });
    function resetform(disablefrom)
    {
        if (checkIfParamIsNullOrUndefined($('#fkcategoryapomiosi').val()) || $('#fkcategoryapomiosi').val() == -1)
        {
            disablefrom = true;
        }
        $(".tblnewrecord").find('[class*="divtd"]').each(function () {
            $(this).css({'background-color': ''});
        });
        $(".tblnewrecord").find('[class*="myfield-newrecord-"]').each(function () {
            if ($(this).attr('name') != 'fkcategoryapomiosi')
            {
                $(this).val('');
                $(this).prop('readonly', true);
                $(this).css({'background-color': ''});
            }
        });
        $(".tblnewrecord").find('[class*="myfield-newrecord-"]').filter('[class*="bs-select"]').each(function () {
            if ($(this).attr('name') == 'fkcategoryapomiosi')
            {
                $(this).prop('disabled', false);
                if (checkIfParamIsNullOrUndefined($(this).val()))
                {
                    $(this).val('-1');
                }
            } else
            {
                $(this).val('-1');
                $(this).prop('disabled', true);
            }
        });
        $(".tblnewrecord").find('[class*="divtd"]').filter('[class*="rocontent"]').each(function () {
            $(this).html('');
        });
        $(".tblnewrecord").find('.myfield-newrecord-mybarcode').prop('readonly', disablefrom);
        $('#fkcategoryapomiosi').focus();
        if (disablefrom == false)
        {
            $(".myfield-newrecord-mybarcode").focus();
        }
    }
    function updateform(result)
    {
        $(".tblnewrecord").find('[class*="divtd"]').each(function () {
            $(this).css({'background-color': ''});
        });
        $(".tblnewrecord").find('[class*="myfield-newrecord-"]').each(function () {
            if ($(this).attr('name') != 'fkcategoryapomiosi')
            {
                $(this).val('');
                $(this).prop('readonly', false);
                $(this).css({'background-color': ''});
            }
        });
        $(".tblnewrecord").find('[class*="myfield-newrecord-"]').filter('[class*="bs-select"]').each(function () {
            if ($(this).attr('name') != 'fkcategoryapomiosi')
            {
                $(this).val('-1');
                $(this).prop('disabled', false);
            }
        });
        $(".divtdmydesc").html(result.data[0].mydesc);

        $(".divtdmonadapolisistitle").html(result.data[0].monadapolisistitle);
        $(".myfield-newrecord-mybarcode").val(result.data[0].mybarcode);
        $(".divtdmyhope").html(result.data[0].myhope);
        $(".divtdmymasteritem").html(result.data[0].mymasteritem);


        $(".tblnewrecord").find('.myfield-newrecord-mybarcode').prop('readonly', true);
        $(".myfield-newrecord-myqty").focus();
    }
    $("<?php echo B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::Get_Identity_Class_New_Record('mybarcode', true); ?>").keyup(function (e) {

        if (e.keyCode == 13) {
            var data = {};
            var metadata = {};
            var alert_divid = '#bootstrap_alert_common';
            var alert_msg = 'Unkown Error1';
            var alert_icon = "check";
            var alert_type = "error";
            var myurl = "<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_DYNPAGE_HELPERPAGE_PARAM3, array('helperpage' => $di->controller_params_array['settings']['Helper_Page_Posts'], 'param1' => 'getrecord', 'param2' => 'vf_erp_my_barcodes_paralaves_antistixisi_m', 'param3' => 'mybarcode')); ?>" + $(this).val() + "/";
            data[$(this).attr('name')] = $(this).val();
            $.ajax({
                url: myurl,
                type: "POST",
                async: true,
                dataType: "json",
                data: {
                    settings: data
                },
                success: function (result) {
                    if (result.success == 1) {
                        alert_type = "success";
                        alert_msg = '<?php echo B2b\Models\CoreModels\PpB2bAdminVfroutepageplugintranslateavailableplugin::Get_Translation(B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::$AvailablePluginAliasName, 'datatablesv11010_inner_home_erp_krestena_my_items_metasiskevasia_proiontaRecordfound1'); ?>';
                        updateform(result);
                    } else
                    {
                        resetform(false);
                        alert_msg = '<?php echo B2b\Models\CoreModels\PpB2bAdminVfroutepageplugintranslateavailableplugin::Get_Translation(B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::$AvailablePluginAliasName, 'datatablesv11010_inner_home_erp_krestena_my_items_metasiskevasia_proiontaNorecordfound2'); ?>';
                        alert_type = "warning";
                        toastrMsg('', alert_msg, alert_type);
                    }

                },
                error: function () {
                    resetform(false);
                    alert_msg = '<?php echo B2b\Models\CoreModels\PpB2bAdminVfroutepageplugintranslateavailableplugin::Get_Translation(B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::$AvailablePluginAliasName, 'datatablesv11010_inner_home_erp_krestena_my_items_metasiskevasia_proiontaUnkownErrorDuringfirststep'); ?>';
                    alert_type = "error";
                    toastrMsg('', alert_msg, alert_type);
                }
            });
            return false;
        }
    });

</script>

