<?php
$di = \Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
$calarrparams = $di->controller_params_array[\CHCrmCParams::$keyarrFullCalendar];
?>
<!-- BEGIN PAGE HEADER-->

<?php
echo Metronic454CCustomHelperAjax::get_div_ajax_small_stack1();
echo Metronic454CCustomHelperAjax::get_div_ajax_full();
echo \B2b\Models\CoreModels\DlB2bAdminMetronic454PluginModalGeneral::Get_Modal_HTML(B2b\Models\CoreModels\DlB2bAdminFullCalendar::Get_Create_Event_Modal_ID());
echo \B2b\Models\CoreModels\DlB2bAdminMetronic454PluginModalGeneral::Get_Modal_HTML(B2b\Models\CoreModels\DlB2bAdminFullCalendar::Get_Create_Event_Modal_Add_Member_ID());
echo \B2b\Models\CoreModels\DlB2bAdminMetronic454PluginModalGeneral::Get_Modal_HTML(B2b\Models\CoreModels\DlB2bAdminFullCalendar::Get_Create_Event_Modal_Add_Trainer_ID());
echo \B2b\Models\CoreModels\DlB2bAdminMetronic454PluginModalGeneral::Get_Modal_HTML(B2b\Models\CoreModels\DlB2bAdminFullCalendar::Get_Create_Event_Modal_Quick_Tpls_ID());
?>
<?php
echo \B2b\Models\CoreModels\PpB2bAdminMetronic454PluginPageHelperHeader::Get_Page_Header();
?>

<!-- END PAGE HEADER-->
<!-- BEGIN MAIN CONTENT -->
<?php
// DLS20161012
echo \B2b\Models\CoreModels\DlB2bAdminFullCalendar::Get_Create_Event_Portlet();
// DLS20161012
echo \B2b\Models\CoreModels\PpB2bAdminMetronic454PluginFullCalendar::Get_Page_FullCalendar();
?>
<!-- END MAIN CONTENT -->

<!-- BEGIN PAGE LEVEL PLUGINS 
<script src="/<?php echo $assetspath; ?>global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js" type="text/javascript"></script>-->
<!-- END MAIN JS -->
<?php
echo MyTags::MyCollectionGenerateCustomMinifyBottom();
?>
<script type="text/javascript">
    runeveryinner();
    var MyModalInitPage = function () {
        //    Form1Click();
    }
    var MyModalOnClose = function () {
        // alert('close');
        //    grid.getDataTable().ajax.reload();
    }
    UIGeneral.init();

<?php
echo B2b\Models\CoreModels\PpB2bAdminMetronic454PluginDataTableAjax::Get_Js_Function_MyRunForm();
?>
    //TableAjax.init('datatable_ajax');
    //UIGeneral.init();
    //MyRunForm();
    LoadFullCalendarv261(null, null, "<?php echo CHCrmCParams::My_get_mykatastima(); ?>", "<?php echo $calarrparams['id']; ?>");
    //$('#private-calendar-go-to-date-btn').click();

</script>