<?php
$di = \Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
?>
<!-- BEGIN PAGE HEADER-->

<?php
echo Metronic454CCustomHelperAjax::get_div_ajax_small_stack1();
echo Metronic454CCustomHelperAjax::get_div_ajax_full();
?>
<?php
//echo \B2b\Models\CoreModels\PpB2bAdminMetronic454PluginPageHelperHeader::Get_Page_Header();
?>

<!-- END PAGE HEADER-->
<!-- BEGIN MAIN CONTENT -->
<?php
echo \B2b\Models\CoreModels\PpB2bAdminMetronic454PluginFullCalendar::Get_Page_FullCalendar();
?>
<!-- END MAIN CONTENT -->

<!-- BEGIN PAGE LEVEL PLUGINS 
<script src="/<?php echo $assetspath; ?>global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js" type="text/javascript"></script>-->
<!-- END MAIN JS -->
<script type="text/javascript">
    runeveryinner();
    var MyModalInitPage = function () {
        //    Form1Click();
    }
    var MyModalOnClose = function () {
        //alert('close');
        //    grid.getDataTable().ajax.reload();
    }
    UIGeneral.init();
    LoadFullCalendarv261();

</script>


