<?php
$di = Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
?>
<link href='<?php echo $assetspath; ?>global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css' rel="stylesheet" type="text/css"/>
<link href='<?php echo $assetspath; ?>global/plugins/bootstrap-fileinput/bootstrap-fileinput.css' rel="stylesheet" type="text/css"/>
<link href='<?php echo $assetspath; ?>global/plugins/bootstrap-switch/css/bootstrap-switch.min.css' rel="stylesheet" type="text/css"/>
<link href='<?php echo $assetspath; ?>global/plugins/jquery-tags-input/jquery.tagsinput.css' rel="stylesheet" type="text/css"/>
<link href='<?php echo $assetspath; ?>global/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css' rel="stylesheet" type="text/css"/>
<link href='<?php echo $assetspath; ?>global/plugins/typeahead/typeahead.css' rel="stylesheet" type="text/css"/>

<div class="modal-dialog modal-full">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal" id="form2" novalidate="novalidate">
        <div class="modal-content" id="modalvars">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h3 class="modal-title"><?php echo $di->controller_params_array['formdata']['modaltitle']; ?></h3>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    You have some form errors. Please check below.
                </div>
                <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button>
                    Your form validation is successful!
                </div>
                <div class="form-body">
                    <?php
                    echo CHMod20130918DuleEditModal::Get_All_Modals_Static_Texts();
                    ?>
                </div>


            </div>
            <div class="modal-footer form">

                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-3 col-md-offset-4">
                                    <button type="submit" class="btn green"><i class="fa fa-check"></i> Submit</button>
                                    <button type="button" class="btn default" data-dismiss="modal">Cancel</button>
                                    <input type="hidden" id="moduleid" name="moduleid" value="<?php echo $di->controller_params_array['moduledata']['modalmoduleid']; ?>"/>
                                    <input type="hidden" id="portletid" name="portletid" value="<?php echo $di->controller_params_array['moduledata']['portletid']; ?>"/>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/jquery-validation/js/additional-methods.min.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-markdown/js/bootstrap-markdown.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-markdown/lib/markdown.js"></script>

<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/fuelux/js/spinner.min.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/bootstrap-fileinput/bootstrap-fileinput.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/jquery.input-ip-address-control-1.0.min.js"></script>
<script src="<?php echo $assetspath; ?>global/plugins/bootstrap-pwstrength/pwstrength-bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/jquery-tags-input/jquery.tagsinput.min.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/typeahead/handlebars.min.js" type="text/javascript"></script>
<script src="<?php echo $assetspath; ?>global/plugins/typeahead/typeahead.bundle.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $assetspath; ?>global/plugins/ckeditor/ckeditor.js"></script>


<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->


<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    var MyModalInitPage = function () {

        $("#demo123").TouchSpin({
            buttondown_class: 'btn green',
            buttonup_class: 'btn green',
            min: 1,
            max: 12,
            stepinterval: 1,
            maxboostedstep: 2,
            prefix: '$'
        });

        $("#touchspin_demo2").TouchSpin({
            buttondown_class: 'btn blue',
            buttonup_class: 'btn blue',
            min: 0,
            max: 100,
            step: 0.1,
            decimals: 2,
            boostat: 5,
            maxboostedstep: 10,
            postfix: '%'
        });

        $("#touchspin_demo3").TouchSpin({
            buttondown_class: 'btn green',
            buttonup_class: 'btn green',
            prefix: "$",
            postfix: "%"
        });

    }

    var handleValidation2 = function () {
        // for more info visit the official plugin documentation: 
        // http://docs.jquery.com/Plugins/Validation

        var form2 = $('#form2');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);

        form2.validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block help-block-error', // default input error message class
            focusInvalid: false, // do not focus the last invalid input
            ignore: "", // validate all fields including form hidden input
            rules: {
                'demo123': {
                    email: true,
                    required: true
                },
                /*email: {
                 required: true,
                 email: true
                 },
                 email: {
                 required: true,
                 email: true
                 },
                 url: {
                 required: true,
                 url: true
                 },
                 number: {
                 required: true,
                 number: true
                 },
                 digits: {
                 required: true,
                 digits: true
                 },
                 creditcard: {
                 required: true,
                 creditcard: true
                 },*/
            },
            invalidHandler: function (event, validator) { //display error alert on form submit  
                alert('invalidHandler');
                success2.hide();
                error2.show();
                Metronic.scrollTo(error2, -200);
            },
            errorPlacement: function (error, element) { // render error placement for each input type
                alert('errorPlacement');
                var icon = $(element).parent('.input-icon').children('i');
                icon.removeClass('fa-check').addClass("fa-warning");
                icon.attr("data-original-title", error.text()).tooltip({'container': 'body'});
            },
            highlight: function (element) { // hightlight error inputs
                alert('highlight');
                $(element)
                        .closest('.form-group').removeClass("has-success").addClass('has-error'); // set error class to the control group   
            },
            unhighlight: function (element) { // revert the change done by hightlight

            },
            success: function (label, element) {
                alert('success');
                var icon = $(element).parent('.input-icon').children('i');
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                icon.removeClass("fa-warning").addClass("fa-check");
            },
            submitHandler: function (form) {
                alert('submithandler');
                success2.show();
                error2.hide();
                form.submit();
                //alert( "Valid: " + form[0].valid() );
                //form[0].submit(); // submit the form
            }
        });


    }
    handleValidation2();
    //$('.portlet .portlet-title a.reload[data-load="true"]').click();

</script>