<?php
$di = \Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
?>
<?php
if (!\MyCustomHelperSession::My_check_is_login()) {
    die('not allowed');
}
?>
<div class="page-sidebar navbar-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" ng-class="{'page-sidebar-menu-closed': settings.layout.pageSidebarClosed}">
        <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
        <li class="sidebar-search-wrapper">
            <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
            <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
            <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
            <form class="sidebar-search sidebar-search-bordered" action="extra_search.html" method="POST">
                <a href="javascript:;" class="remove">
                    <i class="icon-close"></i>
                </a>
                <div class="input-group">
                    <!-- Pan Pan class add (.my-edit-js-control) for modals 06/05/2015 -->
                    <input type="text" class="form-control my-edit-js-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                    </span>
                </div>
            </form>
            <!-- END RESPONSIVE QUICK SEARCH FORM -->
        </li>
        <li class="start nav-item">
            <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/inner_home_index_gym.html">
                <i class="icon-home"></i>
                <span class="title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="javascript:;" class="nav-link nav-toggle">
                <i class="icon-settings"></i>
                <span class="title">Settings</span>
                <span class="arrow "></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/inner_home_settings_static_translates.html" id="sidebar_menu_link_<?php echo $di->controller_params_array['lng']; ?>_inner_home_settings_static_translates">
                        <i class="fa fa-table"></i> Static Translates</span>
                    </a>
                </li>
                <li>
                    <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/--a1--inner_home_settings_modules_edit.html" id="sidebar_menu_link_<?php echo $di->controller_params_array['lng']; ?>_inner_home_settings_modules_edit">
                        <i class="icon-puzzle"></i> Modules</span>
                    </a>
                </li>
                <li>
                    <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/inner_home_settings_tables.html" id="sidebar_menu_link_<?php echo $di->controller_params_array['lng']; ?>_inner_home_settings_tables">
                        <i class="fa fa-table"></i> Tables</span>
                    </a>
                </li>
                <li>
                    <a href="#/ui_select.html">
                        <i class="fa fa-columns"></i> Fields</span>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;" class="nav-link nav-toggle">
                <i class="fa fa-sitemap"></i>
                <span class="title">Sites</span>
                <span class="arrow "></span>
            </a>
            <ul class="sub-menu">
                <li class="nav-item">
                    <a href="javascript:;" class="nav-link nav-toggle">
                        <i class="fa fa-ellipsis-h"></i> Hellenic Mod
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/<?php echo B2b\Models\CoreModels\PpB2bAdminVfroutepage::Get_Page_Name('Inner_Home_Sites_Mod_Articles'); ?>.html" id="sidebar_menu_link_<?php echo $di->controller_params_array['lng']; ?>_<?php echo B2b\Models\CoreModels\PpB2bAdminVfroutepage::Get_Page_Name('Inner_Home_Sites_Mod_Articles'); ?>">
                                <i class="icon-tag"></i> Articles
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_INDEX); ?>#/<?php echo $di->controller_params_array['lng']; ?>/<?php echo $di->controller_params_array['settings']['Inner_Home_Sites_Mod_Categories_Page']; ?>.html" id="sidebar_menu_link_<?php echo $di->controller_params_array['lng']; ?>_<?php echo $di->controller_params_array['settings']['Inner_Home_Sites_Mod_Categories_Page']; ?>">
                                <i class="icon-tag"></i> Categories
                            </a>
                        </li>
                    </ul>
                </li>


            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;">
                <i class="icon-settings"></i>
                <span class="title">AngularJS Features</span>
                <span class="arrow "></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="#/ui_bootstrap.html">
                        <i class="icon-puzzle"></i> UI Bootstrap</span>
                    </a>
                </li>
                <li>
                    <a href="#/file_upload.html">
                        <i class="icon-paper-clip"></i> File Upload</span>
                    </a>
                </li>
                <li>
                    <a href="#/ui_select.html">
                        <i class="icon-check"></i> UI Select</span>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;">
                <i class="icon-wrench"></i>
                <span class="title">jQuery Plugins</span>
                <span class="arrow "></span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="#/form-tools">
                        <i class="icon-puzzle"></i> Form Tools
                    </a>
                </li>
                <li>
                    <a href="#/pickers">
                        <i class="icon-calendar"></i> Date & Time Pickers
                    </a>
                </li>
                <li>
                    <a href="#/dropdowns">
                        <i class="icon-refresh"></i> Custom Dropdowns
                    </a>
                </li>
                <li>
                    <a href="#/tree">
                        <i class="icon-share"></i> Tree View
                    </a>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="icon-briefcase"></i> Datatables
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#/datatables/advanced.html">
                                <i class="icon-tag"></i> Advanced Datatables
                            </a>
                        </li>
                        <li>
                            <a href="#/datatables/ajax.html">
                                <i class="icon-refresh"></i> Ajax Datatables
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="#/profile/dashboard" id="sidebar_menu_link_profile">
                <i class="icon-user"></i>
                <span class="title">User Profile</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#/todo">
                <i class="icon-check"></i>
                <span class="title">Task & Todo</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="../index.html" target="_blank">
                <i class="icon-paper-plane"></i>
                <span class="title">HTML Version</span>
            </a>
        </li>
    </ul>
    <!-- END SIDEBAR MENU -->
</div>