<?php
$di = \Phalcon\DI::getDefault();
$assetspath = $di->controller_params_array['template']['template_admin_path_with_assets_path'];
?>
<?php
if (!\MyCustomHelperSession::My_check_is_login()) {
    die('not allowed');
}
?>
<!-- BEGIN HEADER INNER -->
<div class="page-header-inner">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
        <a href="#/">  
            <img src="<?php echo $di->controller_params_array['custompath']; ?>images/logo.png" alt="logo" class="logo-default"/>
        </a>
        <div class="menu-toggler sidebar-toggler">
            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
        </div>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN MEGA MENU -->
    <!-- DOC: Remove "hor-menu-light" class to have a horizontal menu with theme background instead of white background -->
    <!-- DOC: This is desktop version of the horizontal menu. The mobile version is defined(duplicated) in the responsive menu below along with sidebar menu. So the horizontal menu has 2 seperate versions -->
    <!--<div class="hor-menu  hor-menu-light hidden-sm hidden-xs">
        <ul class="nav navbar-nav">
            <li class="mega-menu-dropdown mega-menu-full" data-hover="megamenu-dropdown" data-close-others="true">
                <a href="javascript:;" class="dropdown-toggle" data-hover="megamenu-dropdown" data-close-others="true">
    <?php //echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('dlquicknavtitle');?>
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <div class="mega-menu-content">
    <?php //echo B2b\Models\CoreModels\DlB2bAdminGeneralHelper::Get_Dashboard_Buttons(false); ?>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div> -->
    <!-- BEGIN HEADER SEARCH BOX -->
    <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
    <form class="search-form hide" action="#" method="GET">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search..." name="query">
            <span class="input-group-btn">
                <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
            </span>
        </div>
    </form>
    <!-- END HEADER SEARCH BOX -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
        <ul class="nav navbar-nav pull-right">

            <!-- BEGIN NOTIFICATION DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_subscriptions">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <i class="fa fa-money"></i>
                    <span class="badge badge-default">
                        28 </span>
                </a>
                <ul class="dropdown-menu">
                    <li class="external">
                        <h3>subscriptionstitle</h3>
                        <a href="#/profile/dashboard">viewalltitle</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 200px;" data-handle-color="#637283">
                            <li>
                                <a href="javascript:;">
                                    <span class="details">
                                        <span class="label label-sm label-danger">
                                            <i class="fa fa-hourglass-end"></i>
                                        </span>
                                        &nbsp;&nbsp;&nbsp;lhgounsimeratitle
                                    </span>
                                    <span class="badge badge-info pull-right">3</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="details">
                                        <span class="label label-sm label-icon label-warning">
                                            <i class="fa fa-hourglass-half"></i>
                                        </span>
                                        &nbsp;&nbsp;&nbsp;lhgountreiesmerestitle
                                    </span>
                                    <span class="badge badge-info pull-right">7</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="details">
                                        <span class="label label-sm label-icon label-info">
                                            <i class="fa fa-hourglass"></i>
                                        </span>
                                        &nbsp;&nbsp;&nbsp;lhgounmiavdomadatitle
                                    </span>
                                    <span class="badge badge-info pull-right">12</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- END NOTIFICATION DROPDOWN -->

            <!-- BEGIN NOTIFICATION DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-extended dropdown-notification dashboard-notes-dropdown" id="header_notification_bar">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <i class="fa fa-sticky-note-o"></i>
                    <span id="notes_badge_count" class="badge badge-default">
                        <?php echo B2b\Models\CoreModels\DlB2bAdminNotesHelper::Get_Notes_Badge_Digit(); ?>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li class="external">
                        <h3><?php echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('simeiwseistitle'); ?></h3>
                        <a href="#/profile/dashboard"><?php echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('viewalltitle');?></a>
                    </li>
                    <li>
                        <ul id="notes_body_container" class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                            <?php echo B2b\Models\CoreModels\DlB2bAdminNotesHelper::Get_Notes(); ?>
                        </ul>
                    </li>
                    <li class="text-center">
                        <div id="notes_button_add_note_container" class="btn-group btn-group-solid" style="padding: 5px;">
                            <a href="javascript:DlDashboardNotes.Add();" class="btn btn-block btn-sm blue add-note" type="button">
                                <i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;<?php echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('addnotetitle');?>
                            </a>
                        </div>
                        <div id="notes_save_cancel_note_container" class="btn-group btn-group-solid" style="display: none; padding: 5px;">
                            <a href="javascript:DlDashboardNotes.Save();" class="btn btn-sm green-meadow save-note" type="button">
                                <i class="fa fa-save"></i>&nbsp;&nbsp;&nbsp;<?php echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('savenotetitle');?>
                            </a>
                            <a href="javascript:DlDashboardNotes.Cancel();" class="btn btn-sm red-flamingo cancel-note" type="button">
                                <i class="fa fa-trash"></i>&nbsp;&nbsp;&nbsp;<?php echo B2b\Models\CoreModels\PpB2bAdminVftranslate::getKeyvalueFromKeyname('cancelnotetitle');?>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <!-- END NOTIFICATION DROPDOWN -->

            <!-- BEGIN INBOX DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <!-- <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <i class="icon-envelope-open"></i>
                    <span class="badge badge-default">
                        4 </span>
                </a>
                <ul class="dropdown-menu">
                    <li class="external">
                        <h3>You have <span class="bold">7 New</span> Messages</h3>
                        <a href="#/profile/dashboard">view all</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                            <li>
                                <a href="#/profile/dashboard">
                                    <span class="photo">
                                        <img src="<?php echo $assetspath; ?>/layouts/layout/img/avatar2.jpg" class="img-circle" alt="">
                                    </span>
                                    <span class="subject">
                                        <span class="from">
                                            Lisa Wong </span>
                                        <span class="time">Just Now </span>
                                    </span>
                                    <span class="message">
                                        Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                </a>
                            </li>
                            <li>
                                <a href="#/profile/dashboard">
                                    <span class="photo">
                                        <img src="<?php echo $assetspath; ?>layouts/layout/img/avatar3.jpg" class="img-circle" alt="">
                                    </span>
                                    <span class="subject">
                                        <span class="from">
                                            Richard Doe </span>
                                        <span class="time">16 mins </span>
                                    </span>
                                    <span class="message">
                                        Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                </a>
                            </li>
                            <li>
                                <a href="#/profile/dashboard">
                                    <span class="photo">
                                        <img src="<?php echo $assetspath; ?>layouts/layout/img/avatar1.jpg" class="img-circle" alt="">
                                    </span>
                                    <span class="subject">
                                        <span class="from">
                                            Bob Nilson </span>
                                        <span class="time">2 hrs </span>
                                    </span>
                                    <span class="message">
                                        Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                </a>
                            </li>
                            <li>
                                <a href="#/profile/dashboard">
                                    <span class="photo">
                                        <img src="<?php echo $assetspath; ?>layouts/layout/img/avatar2.jpg" class="img-circle" alt="">
                                    </span>
                                    <span class="subject">
                                        <span class="from">
                                            Lisa Wong </span>
                                        <span class="time">40 mins </span>
                                    </span>
                                    <span class="message">
                                        Vivamus sed auctor 40% nibh congue nibh... </span>
                                </a>
                            </li>
                            <li>
                                <a href="#/profile/dashboard">
                                    <span class="photo">
                                        <img src="<?php echo $assetspath; ?>layouts/layout/img/avatar3.jpg" class="img-circle" alt="">
                                    </span>
                                    <span class="subject">
                                        <span class="from">
                                            Richard Doe </span>
                                        <span class="time">46 mins </span>
                                    </span>
                                    <span class="message">
                                        Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li> -->
            <!-- END INBOX DROPDOWN -->

            <!-- BEGIN TODO DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <!-- <li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <i class="fa fa-facebook"></i>
                    <span class="badge badge-default">
                        3 </span>
                </a>
                <ul class="dropdown-menu extended tasks">
                    <li class="external">
                        <h3>You have <span class="bold">12 pending</span> tasks</h3>
                        <a href="#/todo">view all</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">New release v1.2 </span>
                                        <span class="percent">30%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">40% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">Application deployment</span>
                                        <span class="percent">65%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">65% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">Mobile app release</span>
                                        <span class="percent">98%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">98% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">Database migration</span>
                                        <span class="percent">10%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">10% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">Web server upgrade</span>
                                        <span class="percent">58%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">58% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">Mobile development</span>
                                        <span class="percent">85%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">85% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">New UI release</span>
                                        <span class="percent">38%</span>
                                    </span>
                                    <span class="progress progress-striped">
                                        <span style="width: 38%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">38% Complete</span></span>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li> -->
            <!-- END TODO DROPDOWN -->

            <!-- BEGIN LANGUAGE BAR -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-language hide">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <img alt="" src="<?php echo $assetspath; ?>/global/img/flags/us.png">
                    <span class="langname">
                        EN </span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-default">
                    <li class="active">
                        <a href="#">
                            <img alt="" src="<?php echo $assetspath; ?>/global/img/flags/us.png"> English </a>
                    </li>
                    <li>
                        <a href="#">
                            <img alt="" src="<?php echo $assetspath; ?>/global/img/flags/de.png"> German </a>
                    </li>
                    <li>
                        <a href="#">
                            <img alt="" src="<?php echo $assetspath; ?>/global/img/flags/ru.png"> Russian </a>
                    </li>
                    <li>	
                        <a href="#">
                            <img alt="" src="<?php echo $assetspath; ?>/global/img/flags/fr.png"> French </a>
                    </li>
                </ul>
            </li>
            <!-- END LANGUAGE BAR -->

            <!-- BEGIN USER LOGIN DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-user">
                <a href="#" class="dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
                    <img alt="" class="img-circle" src="<?php echo $di->controller_params_array['custompath'] ?>images/users/<?php
                    $rowuser = json_decode(MyCustomHelperSession::My_get_param_val('jsonrowuser'), true);
                    echo $rowuser['id'];
                    ?>-avatar.jpg"/>
                    <span class="username username-hide-on-mobile">
                        <?php echo $rowuser['username']; ?> </span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-default">
                    <li>
                        <a href="#/profile/dashboard">
                            <i class="icon-user"></i> My Profile </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="icon-calendar"></i> My Calendar </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
                                3 </span>
                        </a>
                    </li>
                    <li>
                        <a href="#/todo">
                            <i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
                                7 </span>
                        </a>
                    </li>
                    <li class="divider">
                    </li>
                    <li>
                        <a class="lock-user" href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_LOCK); ?>">

                            <i class="icon-lock"></i> Lock Screen </a>
                    </li>
                    <li>
                        <a href="<?php echo MyCustomHelperPages::makePage(CHCrmCConstantsPages::CONST_PAGES_ADMIN_LOGIN); ?>">
                            <i class="icon-key"></i> Log Out </a>
                    </li>
                </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->

            <!-- BEGIN QUICK SIDEBAR TOGGLER -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-quick-sidebar-toggler">
                <a href="javascript:;" class="dropdown-toggle">
                    <i class="icon-logout"></i>
                </a>
            </li>
            <!-- END QUICK SIDEBAR TOGGLER -->
        </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->
</div>
<!-- END HEADER INNER --> 