<!-- BEGIN REGISTRATION FORM -->
<form class="register-form" action="" method="post">
    <h3>Sign Up</h3>
    <p class="hint">
        Enter your personal details below:
    </p>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Full Name</label>
        <input class="form-control placeholder-no-fix" type="text" placeholder="First Name" name="fname"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Full Name</label>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Last Name" name="lname"/>
    </div>
    <div class="form-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Email</label>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="email"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Address</label>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Address" name="address"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">City/Town</label>
        <input class="form-control placeholder-no-fix" type="text" placeholder="City/Town" name="city"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Country</label>
        <select name="myfkcountryshorttiltle" id="myfkcountryshorttiltle" class="form-control select2me">
            <?php
            $classname = MyCustomHelperClassTools::My_Core_Get_Classname('corecountry');
            $valsarray = \B2b\Models\CoreModels\PpB2bAdminGetComplex::GetComplex($classname, 0, -1, array('fklng' => array('value' => MyCustomHelperLng::My_get_current_lng_id())), array('title' => 'asc'));
            $newvalsarray = array();
            foreach ($valsarray as $key => $value) {
                $newvalsarray[$value['shorttitle']] = $value['title'];
            }
            $optionvals = MyCustomHelpeHtmlSelectList::getHtmlSelectList($newvalsarray);
            $optionvals = '<option value="">Country</option>' . $optionvals;
            echo $optionvals;
            ?>
        </select>
    </div>
    <p class="hint">
        Enter your account details below:
    </p>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Username</label>
        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="userpassword" placeholder="Password" name="userpassword"/>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="rpassword"/>
    </div>
    <div class="form-group margin-top-20 margin-bottom-20">
        <label class="check">
            <input type="checkbox" name="tnc"/> I agree to the <a href="#">
                Terms of Service </a>
            & <a href="#">
                Privacy Policy </a>
        </label>
        <div id="register_tnc_error">
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="register-back-btn" class="btn btn-default">Back</button>
        <button type="submit" id="register-submit-btn" class="btn btn-success uppercase pull-right">Submit</button>
        <input type="hidden" name='sessid' value="<?php echo $this->session->getId(); ?>"/>
        <input type="hidden" name='formpage' value="registration"/>
    </div>
</form>
<!-- END REGISTRATION FORM -->